# NumPy - Numerical Python Library

In [1]:
#Import Numpy

import numpy as np

In [2]:
# Create a simple array from the List

arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
#Dimension of Array
print(arr.ndim)

2


In [4]:
#Shape of an Array
print(arr.shape)

(2, 4)


In [5]:
#Dimensions of the Array

print(type(arr))

<class 'numpy.ndarray'>


In [6]:
#Dimensions of the Array

print(arr.data)

In [7]:
b = np.array([[20,21,22],[25,26,27],[30,31,32]])
print(b,"\n")

[[20 21 22]
 [25 26 27]
 [30 31 32]] 



In [8]:
b.dtype

dtype('int32')

In [9]:
b.itemsize

4

In [10]:
b.size

9

In [11]:
b.shape

(3, 3)

In [12]:
b = np.array([[20,21,22],[25,26,27],[30,31,32]], dtype=np.float64)
print(b,"\n")
print(b.dtype,"\n")
print(b.itemsize)

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

float64 

8


In [13]:
z = np.array([[20,21,22],[25,26,27],[30,31,32]], dtype=np.complex64)
t = np.array([[20,21,22],[25,26,27],[30,31,32]], dtype=np.complex128)
print(z,"\n")
print(z.dtype,"\n")
print(z.itemsize,"\n")
print(t,"\n")
print(t.dtype,"\n")
print(t.itemsize,"\n")

[[20.+0.j 21.+0.j 22.+0.j]
 [25.+0.j 26.+0.j 27.+0.j]
 [30.+0.j 31.+0.j 32.+0.j]] 

complex64 

8 

[[20.+0.j 21.+0.j 22.+0.j]
 [25.+0.j 26.+0.j 27.+0.j]
 [30.+0.j 31.+0.j 32.+0.j]] 

complex128 

16 



In [14]:
#Sum value of an Array
print(np.sum(b))

234.0


In [15]:
#Sum Value along a specified axis

print(b,"\n")
print(np.sum(b, axis=0))
print(np.sum(b, axis=1))

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

[75. 78. 81.]
[63. 78. 93.]


In [16]:
#Minimum Value
print(b,"\n")
print(np.amin(b))
print(np.amin(b,axis=0))
print(np.amin(b,axis=1))

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

20.0
[20. 21. 22.]
[20. 25. 30.]


In [17]:
#Maximum Value
print(np.max(b))
print(np.max(b,axis=0))
print(np.max(b,axis=1))
print(type(b))

32.0
[30. 31. 32.]
[22. 27. 32.]
<class 'numpy.ndarray'>


In [18]:
#Mean
print(np.mean(b))
print(np.mean(b,axis=0))
print(np.mean(b,axis=1))
print(type(b))

26.0
[25. 26. 27.]
[21. 26. 31.]
<class 'numpy.ndarray'>


In [19]:
#Variance
print(b,"\n")
print(np.var(b))
print(np.var(b,axis=0))
print(np.var(b,axis=1))

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

17.333333333333332
[16.66666667 16.66666667 16.66666667]
[0.66666667 0.66666667 0.66666667]


In [20]:
# Weighted Average
print(np.average(b))

26.0


In [21]:
c = np.array([2,4,6, 1,3,5, 8,10,12, 7,9,11])
print(c)

[ 2  4  6  1  3  5  8 10 12  7  9 11]


In [22]:
weight = np.array([0.25,0.5,0.25,0.5,0.25,0.5,0.25,0.5,0.25,0.5,0.25,0.5])
print(weight)

[0.25 0.5  0.25 0.5  0.25 0.5  0.25 0.5  0.25 0.5  0.25 0.5 ]


In [23]:
print(np.average(c, weights=weight))

6.444444444444445


In [24]:
#Percentile
print(c,"\n")
print(np.percentile(c,5,0))
print(np.percentile(c,8,0))
print(np.percentile(b,5,1))
print(np.percentile(b,5,0))
print(np.percentile(b,4,0))
print(np.percentile(b,4,1))

[ 2  4  6  1  3  5  8 10 12  7  9 11] 

1.55
1.88
[20.1 25.1 30.1]
[20.5 21.5 22.5]
[20.4 21.4 22.4]
[20.08 25.08 30.08]


In [25]:
# Peak to Peak
print(b,"\n")
print(c,"\n")
print(np.ptp(c,0))
print(np.ptp(b,0))
print(np.ptp(b,1))

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

[ 2  4  6  1  3  5  8 10 12  7  9 11] 

11
[10. 10. 10.]
[2. 2. 2.]


In [27]:
print(b,"\n")
print(b.shape,"\n")
print(b.reshape(3,3),"\n")
print(b)


[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

(3, 3) 

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]]


In [28]:
b = np.array([[20,100,22],[25,0,27],[99,31,32],[33,245,789]])
print(b,"\n")
print(c,"\n")
print(np.ptp(c,0))
print(np.ptp(b,0))
print(np.ptp(b,1))

[[ 20 100  22]
 [ 25   0  27]
 [ 99  31  32]
 [ 33 245 789]] 

[ 2  4  6  1  3  5  8 10 12  7  9 11] 

11
[ 79 245 767]
[ 80  27  68 756]


In [29]:
print(b,"\n")
print(b.shape,"\n")
print(b.reshape(3,4),"\n")
print(b)


[[ 20 100  22]
 [ 25   0  27]
 [ 99  31  32]
 [ 33 245 789]] 

(4, 3) 

[[ 20 100  22  25]
 [  0  27  99  31]
 [ 32  33 245 789]] 

[[ 20 100  22]
 [ 25   0  27]
 [ 99  31  32]
 [ 33 245 789]]


In [30]:
#Slicing
e=[25,35,50,55,70,85,95]
print(e[0:4],"\n")
print(e[-1])

[25, 35, 50, 55] 

95


In [31]:
#2D Array
l=np.array([[23,25,27,29],[43,45,47,49],[62,66,68,70]])
print(l,"\n")
print(l[0,3],"\n")
print(l[1,2],"\n")
print(l[2,3],"\n")
print(l[0,1],"\n")
print(l[0:2,1],"\n")
print(l[-1],"\n")
print(l[-1,0:2],"\n")

[[23 25 27 29]
 [43 45 47 49]
 [62 66 68 70]] 

29 

47 

70 

25 

[25 45] 

[62 66 68 70] 

[62 66] 



# STACKING

In [32]:
d=np.arange(12).reshape(3,4)
print(d,"\n")
f=np.arange(12,24).reshape(3,4)
print(f)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [33]:
print(d,"\n")
print(f,"\n")
print(np.vstack((d,f)),"\n")
print(np.vstack((d,f)),"\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 



In [34]:
x=np.array([2,8,10,35,55,60])
y=np.array([1,7,9,34,54,59])
print(x,"\n","\n")
print(y,"\n")
print(x+y,"\n")
print(x-y,"\n")
print(x*y,"\n")
print(x/y,"\n")
print(x//y)

[ 2  8 10 35 55 60] 
 

[ 1  7  9 34 54 59] 

[  3  15  19  69 109 119] 

[1 1 1 1 1 1] 

[   2   56   90 1190 2970 3540] 

[2.         1.14285714 1.11111111 1.02941176 1.01851852 1.01694915] 

[2 1 1 1 1 1]


In [35]:
print(np.zeros((4,3)),"\n")
print(np.ones((100,100)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [36]:
from numpy import random
x =  random.randint(100)
print(x)

5


In [37]:
#Generate Random Float
x = random.rand(5)
print(x)

[0.56235067 0.30849654 0.07468735 0.26522336 0.45244131]


In [38]:
#Generate Random Array
from numpy import random
x = random.randint(100, size=(15))
print(x)

[64 27 69 42 55 97 35 81 80 42 68 13 78 53 95]


In [43]:
#Creating scalars in Numpy
#numpy.asscalar()
import numpy as np
in_arr = np.array([8])
print("Input array is", in_arr)
out_scalar = np.ndarray(in_arr)
print("Output scalar from input array", out_scalar)

Input array is [8]
Output scalar from input array [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 1.81816158e-321 1.24610723e-306 1.29061142e-306]


# Creating Vector in Numpy

In [44]:
#import numpy
import numpy as np

#Creating 1-D List
list1 = [1, 2, 3]

#Creating 1-D List vertical
list2 = [[10],
        [20],
        [30]]

#Creating vactor1

vector1 = np.array(list1)
vector2 = np.array(list2)

print("Horizontal Vector")
print(vector1)

print("--------------------")

print("Vertical Vector")
print(vector2)


Horizontal Vector
[1 2 3]
--------------------
Vertical Vector
[[10]
 [20]
 [30]]


# Creating matrix in Numpy

In [45]:
import numpy as np
a=np.matrix('1 2; 3 4')
print("via string input : \n", a, "\n\n")

#array-Like input
b = np.matrix([[5, 6, 7],[4, 6]])
print("via array-Like input : \n", b)

via string input : 
 [[1 2]
 [3 4]] 


via array-Like input : 
 [[list([5, 6, 7]) list([4, 6])]]


c:\Users\Akash\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\matrixlib\defmatrix.py:145: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = N.array(data, dtype=dtype, copy=copy)


# Matrix multiplication in Numpy

In [46]:
import numpy as np
A = 5

B = [[6,7],
    [8,9]]

print(np.dot(A,B))

[[30 35]
 [40 45]]


In [47]:
import numpy as np
A = [[6,7],
    [8,9]]

B = [[1,3],
    [5,7]]

print(np.dot(A,B))

[[41 67]
 [53 87]]


# Percentile and Interquartile in numpy

In [48]:
import numpy as np
data = [32, 36, 46, 47, 56, 69, 75, 79, 79, 88, 89, 91, 92, 93, 96, 97, 101, 105, 112, 116]

#first quartile(Q1)

Q1 = np.median(data[:10])

#third Quartile

Q3 = np.median(data[10:])

#interquartile range

IQR = Q3-Q1

print(IQR)

34.0


# Array Broadcasting in Numpy

In [49]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])

a * b

array([2., 4., 6.])

In [50]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])